### ISSUE TITLE
JS minified version not copied in _site

### ISSUE THREAD

**Issue by hbbio** [moshen/jekyll-asset_bundler#29]
I'm using jekyll 2.5.3 with the following lines in `_config.yml`:

``` yaml
asset_bundler:
  compress:
    js: closure
```

and I'm invoking in my code:

```
{% bundle %}
  - assets/js/code.js
{% endbundle %}
```

When I run `jekyll build`, the `_asset_bundler_cache` contains the minified version of code.js (and `closure-compiler` is present in Gemfile), but the `_site` directory contains the original, non-minified version.

Are some other parameters necessary, or is this another issue?

**Comment by moshen** [comment]
No `bundles` folder? Also, relative paths aren't supported.  Have you tried changing to an absolute path?

**Comment by hbbio** [comment]
I changed for:

```
{% bundle %}
  - /assets/js/code.js
{% endbundle %}
```

and deleted both `_site` and `_asset_bundler_cache` before running `jekyll build`.
- There is no `bundles` folder
- The minified code is present in `_asset_bundler_cache`
- `_site/assets/js/code.js` is not minified

**Comment by hbbio** [comment]
After reinstalling gems, I now have the `bundles` folder inside `_site`.
Turns out the original version is present as well since it is necessary to exclude it in `_config.yml`. I thought this would be done automatically for files referenced in bundles.

**Comment by moshen** [comment]
Correct, [removing bundled files is a configuration option](https://github.com/moshen/jekyll-asset_bundler/tree/ec2b2cd8dd8d622d3ada6bb1171a1f5c187c8448#configuration).

When you reinstalled gems, did you update/change any versions (just curious).
